In [32]:
import pandas as pd

# Remove the limit on the number of rows and columns to display
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)

In [33]:
X_geo = pd.read_csv("data/train.csv")
X_meteo = pd.read_parquet("data/meteo.parquet")

In [34]:
print(X_geo.shape)
print(X_meteo.shape)

(85571, 26)
(695160, 82)

In [35]:
X_geo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85571 entries, 0 to 85570
Data columns (total 26 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   date                                85571 non-null  object
 1   France                              85571 non-null  float64
 2   Auvergne-Rhône-Alpes                85571 non-null  float64
 3   Bourgogne-Franche-Comté             85571 non-null  float64
 4   Bretagne                            85571 non-null  float64
 5   Centre-Val de Loire                 85571 non-null  float64
 6   Grand Est                           85571 non-null  float64
 7   Hauts-de-France                     85571 non-null  float64
 8   Normandie                           85571 non-null  float64
 9   Nouvelle-Aquitaine                  85571 non-null  float64
 10  Occitanie                           85571 non-null  float64
 11  Pays de la Loire                    85571 non-null  float64
 12  Provence-Alpes-Côte d'Azur          85571 non-null  float64
 13  Île-de-France                       85571 non-null  float64
 14  Montpellier Méditerranée Métropole  74562 non-null  float64
 15  Métropole Européenne de Lille       80285 non-null  float64
 16  Métropole Grenoble-Alpes-Métropole  77823 non-null  float64
 17  Métropole Nice Côte d'Azur          77822 non-null  float64
 18  Métropole Rennes Métropole          77912 non-null  float64
 19  Métropole Rouen Normandie           72855 non-null  float64
 20  Métropole d'Aix-Marseille-Provence  80278 non-null  float64
 21  Métropole de Lyon                   80269 non-null  float64
 22  Métropole du Grand Nancy            77914 non-null  float64
 23  Métropole du Grand Paris            84412 non-null  float64
 24  Nantes Métropole                    82972 non-null  float64
 25  Toulouse Métropole                  77915 non-null  float64
dtypes: float64(25), object(1)
memory usage: 17.0+ MB

In [36]:
X_meteo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 695160 entries, 0 to 695159
Data columns (total 82 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   numer_sta                      695160 non-null  object
 1   date                           695160 non-null  datetime64[ms, Europe/Berlin]
 2   pmer                           650676 non-null  float64
 3   tend                           686386 non-null  float64
 4   cod_tend                       686386 non-null  object
 5   dd                             692663 non-null  float64
 6   ff                             692750 non-null  float64
 7   t                              685752 non-null  float64
 8   td                             685259 non-null  float64
 9   u                              685295 non-null  float64
 10  vv                             653105 non-null  float64
 11  ww                             651840 non-null  object
 12  w1                             122564 non-null  object
 13  w2                             72427 non-null   object
 14  n                              350063 non-null  float64
 15  nbas                           565401 non-null  object
 16  hbas                           401726 non-null  float64
 17  cl                             109514 non-null  object
 18  cm                             80769 non-null   object
 19  ch                             67699 non-null   object
 20  pres                           686553 non-null  float64
 21  niv_bar                        5685 non-null    float64
 22  geop                           28870 non-null   object
 23  tend24                         673542 non-null  float64
 24  tn12                           169784 non-null  float64
 25  tn24                           5403 non-null    float64
 26  tx12                           169784 non-null  float64
 27  tx24                           5403 non-null    float64
 28  tminsol                        556234 non-null  float64
 29  sw                             0 non-null       object
 30  tw                             0 non-null       float64
 31  raf10                          675270 non-null  float64
 32  rafper                         686752 non-null  float64
 33  per                            689595 non-null  float64
 34  etat_sol                       451056 non-null  object
 35  ht_neige                       531010 non-null  float64
 36  ssfrai                         41860 non-null   float64
 37  perssfrai                      41860 non-null   float64
 38  rr1                            677903 non-null  float64
 39  rr3                            682856 non-null  float64
 40  rr6                            671769 non-null  float64
 41  rr12                           668424 non-null  float64
 42  rr24                           661772 non-null  float64
 43  phenspe1                       0 non-null       float64
 44  phenspe2                       0 non-null       float64
 45  phenspe3                       0 non-null       float64
 46  phenspe4                       0 non-null       object
 47  nnuage1                        401621 non-null  float64
 48  ctype1                         101400 non-null  object
 49  hnuage1                        381798 non-null  float64
 50  nnuage2                        204924 non-null  float64
 51  ctype2                         50905 non-null   object
 52  hnuage2                        199977 non-null  float64
 53  nnuage3                        90746 non-null   float64
 54  ctype3                         23239 non-null   object
 55  hnuage3                        90465 non-null   float64
 56  nnuage4                        2387 non-null    object
 57  ctype4                         21895 non-null   object
 58  hnuage4                        2387 non-null    float64
 59  coordonnees                    695160 non-null  object
 60  nom                            695160 non-null  object
 61  type_de_tendance_barometrique  686386 non-null  object
 62  temps_passe_1                  122564 non-null  object
 63  temps_present                  651840 non-null  object
 64  tc                             685752 non-null  float64
 65  tn12c                          169784 non-null  float64
 66  tn24c                          5403 non-null    float64
 67  tx12c                          169784 non-null  float64
 68  tx24c                          5403 non-null    float64
 69  tminsolc                       556234 non-null  float64
 70  latitude                       695160 non-null  float64
 71  longitude                      695160 non-null  float64
 72  altitude                       695160 non-null  int64
 73  libgeo                         695160 non-null  object
 74  codegeo                        695160 non-null  object
 75  nom_epci                       695160 non-null  object
 76  code_epci                      695160 non-null  object
 77  nom_dept                       695160 non-null  object
 78  code_dep                       695160 non-null  object
 79  nom_reg                        695160 non-null  object
 80  code_reg                       695160 non-null  object
 81  mois_de_l_annee                695160 non-null  int64
dtypes: datetime64[ms, Europe/Berlin](1), float64(48), int64(2), object(31)
memory usage: 434.9+ MB

In [37]:
X_geo.head()

,date,France,Auvergne-Rhône-Alpes,Bourgogne-Franche-Comté,Bretagne,Centre-Val de Loire,Grand Est,Hauts-de-France,Normandie,Nouvelle-Aquitaine,Occitanie,Pays de la Loire,Provence-Alpes-Côte d'Azur,Île-de-France,Montpellier Méditerranée Métropole,Métropole Européenne de Lille,Métropole Grenoble-Alpes-Métropole,Métropole Nice Côte d'Azur,Métropole Rennes Métropole,Métropole Rouen Normandie,Métropole d'Aix-Marseille-Provence,Métropole de Lyon,Métropole du Grand Nancy,Métropole du Grand Paris,Nantes Métropole,Toulouse Métropole
0,2017-02-13 01:30:00+01:00,62307.0,8196.0,2606.0,3310.0,2734.0,5905.0,6884.0,4016.0,5778.0,4607.0,3902.0,5086.0,9284.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4774.0,NaN,NaN
1,2017-02-13 02:00:00+01:00,61729.0,8248.0,2695.0,3427.0,2657.0,6012.0,6697.0,3995.0,5577.0,4529.0,3962.0,4995.0,8934.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4660.0,NaN,NaN
2,2017-02-13 02:30:00+01:00,61430.0,8302.0,2774.0,3281.0,2632.0,5941.0,6636.0,3881.0,5560.0,4509.0,3771.0,5122.0,9023.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4625.0,NaN,NaN
3,2017-02-13 03:00:00+01:00,59678.0,8199.0,2663.0,3119.0,2557.0,5857.0,6456.0,3780.0,5368.0,4392.0,3607.0,4846.0,8835.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4532.0,NaN,NaN
4,2017-02-13 03:30:00+01:00,58697.0,8186.0,2728.0,3042.0,2511.0,5822.0,6341.0,3709.0,5126.0,4306.0,3510.0,4719.0,8697.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4489.0,NaN,NaN

In [38]:
X_meteo.head()

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,vv,ww,w1,w2,n,nbas,hbas,cl,cm,ch,pres,niv_bar,geop,tend24,tn12,tn24,tx12,tx24,tminsol,sw,tw,raf10,rafper,per,etat_sol,ht_neige,ssfrai,perssfrai,rr1,rr3,rr6,rr12,rr24,phenspe1,phenspe2,phenspe3,phenspe4,nnuage1,ctype1,hnuage1,nnuage2,ctype2,hnuage2,nnuage3,ctype3,hnuage3,nnuage4,ctype4,hnuage4,coordonnees,nom,type_de_tendance_barometrique,temps_passe_1,temps_present,tc,tn12c,tn24c,tx12c,tx24c,tminsolc,latitude,longitude,altitude,libgeo,codegeo,nom_epci,code_epci,nom_dept,code_dep,nom_reg,code_reg,mois_de_l_annee
0,07020,2017-09-23 02:00:00+02:00,102290.0,0.0,4,160.0,4.9,287.25,283.45,78.0,18000.0,2,0,None,25.0,2,2500.0,30,23,10,102190.0,NaN,None,180.0,NaN,NaN,NaN,NaN,NaN,None,NaN,6.5,7.1,-10.0,None,NaN,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,None,2.0,3,2500.0,NaN,None,NaN,NaN,None,NaN,None,None,NaN,b'\x01\x01\x00\x00\x00\x9f9\xebS\x8e\t\xff\xbf...,PTE DE LA HAGUE,"Stationnaire, la pression atmosphérique est la...",Nuages ne couvrant pas plus de la moitié du ci...,État du ciel inchangé dans l’ensemble,14.1,NaN,NaN,NaN,NaN,NaN,49.725167,-1.939833,6,La Hague,50041,CA du Cotentin,200067205,Manche,50,Normandie,28,9
1,07558,2017-09-23 02:00:00+02:00,102180.0,-40.0,8,30.0,2.4,285.75,282.95,83.0,20000.0,0,None,None,NaN,None,NaN,None,None,None,93940.0,NaN,None,160.0,NaN,NaN,NaN,NaN,283.75,None,NaN,3.5,3.5,-10.0,None,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,None,None,NaN,"b""\x01\x01\x00\x00\x00\x0e-\xb2\x9d\xef'\x08@\...",MILLAU,"Stationnaire ou en hausse, puis en baisse, ou ...",None,On n’a pas observé d’évolution des nuages ou o...,12.6,NaN,NaN,NaN,NaN,10.6,44.118500,3.019500,712,Millau,12145,CC de Millau Grands Causses,241200567,Aveyron,12,Occitanie,76,9
2,07661,2017-09-23 05:00:00+02:00,102090.0,-110.0,7,60.0,3.4,289.85,288.75,93.0,NaN,0,2,None,90.0,7,800.0,36,None,None,100500.0,NaN,None,150.0,NaN,NaN,NaN,NaN,NaN,None,NaN,4.5,4.8,-10.0,None,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,None,7.0,7,600.0,NaN,None,NaN,NaN,None,NaN,None,None,NaN,"b""\x01\x01\x00\x00\x00\x82\xfd\xd7\xb9i\xc3\x1...",CAP CEPET,En baisse,Nuages couvrant plus de la moitié du ciel pend...,On n’a pas observé d’évolution des nuages ou o...,16.7,NaN,NaN,NaN,NaN,NaN,43.079333,5.940833,115,Saint-Mandrier-sur-Mer,83153,Métropole Toulon-Provence-Méditerranée,248300543,Var,83,Provence-Alpes-Côte d'Azur,93,9
3,07117,2017-09-23 08:00:00+02:00,102070.0,-50.0,6,90.0,1.9,283.55,281.85,89.0,NaN,None,None,None,NaN,None,NaN,None,None,None,101360.0,NaN,None,-140.0,283.55,NaN,288.65,NaN,NaN,None,NaN,2.9,3.2,-10.0,None,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,None,None,NaN,b'\x01\x01\x00\x00\x00\x18_\xb4\xc7\x0b\xc9\x0...,PLOUMANAC'H,"En baisse, puis stationnaire, ou en baisse, pu...",None,None,10.4,10.4,NaN,15.5,NaN,NaN,48.825833,-3.473167,55,Perros-Guirec,22168,CA Lannion-Trégor Communauté,200065928,Côtes-d'Armor,22,Bretagne,53,9
4,07621,2017-09-23 11:00:00+02:00,101950.0,-30.0,6,340.0,1.0,290.25,286.95,81.0,29000.0,0,None,None,NaN,None,NaN,None,None,None,97720.0,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,2.6,-10.0,None,0.0,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,None,NaN,None,None,NaN,b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00...,TARBES-OSSUN,"En baisse, puis stationnaire, ou en baisse, pu...",None,On n’a pas observé d’évolution des nuages ou o...,17.1,NaN,NaN,NaN,NaN,NaN,43.188000,0.000000,360,Louey,65284,CA Tarbes-Lourdes-Pyrénées,200069300,Hautes-Pyrénées,65,Occitanie,76,9

In [39]:
# Drop all NaN columns
print(X_meteo.shape)

(695160, 82)

In [40]:
nan_percent = X_meteo.isna().mean().sort_values(ascending=False)
print(nan_percent)

sw                               1.000000
tw                               1.000000
phenspe4                         1.000000
phenspe3                         1.000000
phenspe2                         1.000000
phenspe1                         1.000000
nnuage4                          0.996566
hnuage4                          0.996566
tx24c                            0.992228
tn24c                            0.992228
tx24                             0.992228
tn24                             0.992228
niv_bar                          0.991822
ctype4                           0.968504
ctype3                           0.966570
geop                             0.958470
perssfrai                        0.939784
ssfrai                           0.939784
ctype2                           0.926772
ch                               0.902614
w2                               0.895812
cm                               0.883812
hnuage3                          0.869864
nnuage3                          0.869460
ctype1                           0.854134
cl                               0.842462
temps_passe_1                    0.823690
w1                               0.823690
tx12                             0.755763
tn12c                            0.755763
tx12c                            0.755763
tn12                             0.755763
hnuage2                          0.712330
nnuage2                          0.705213
n                                0.496428
hnuage1                          0.450777
nnuage1                          0.422261
hbas                             0.422110
etat_sol                         0.351148
ht_neige                         0.236133
tminsolc                         0.199848
tminsol                          0.199848
nbas                             0.186661
pmer                             0.063991
ww                               0.062317
temps_present                    0.062317
vv                               0.060497
rr24                             0.048029
rr12                             0.038460
rr6                              0.033648
tend24                           0.031098
raf10                            0.028612
rr1                              0.024825
rr3                              0.017700
td                               0.014243
u                                0.014191
t                                0.013534
tc                               0.013534
tend                             0.012622
cod_tend                         0.012622
type_de_tendance_barometrique    0.012622
pres                             0.012381
rafper                           0.012095
per                              0.008005
dd                               0.003592
ff                               0.003467
numer_sta                        0.000000
date                             0.000000
coordonnees                      0.000000
nom                              0.000000
latitude                         0.000000
longitude                        0.000000
altitude                         0.000000
libgeo                           0.000000
codegeo                          0.000000
nom_epci                         0.000000
code_epci                        0.000000
nom_dept                         0.000000
code_dep                         0.000000
nom_reg                          0.000000
code_reg                         0.000000
mois_de_l_annee                  0.000000
dtype: float64

In [41]:
# On drop les features avec >90% de NaN, features peu utiles par ailleurs
X_meteo.drop(columns=nan_percent[nan_percent > 0.9].index, inplace=True)
X_meteo.head()

,numer_sta,date,pmer,tend,cod_tend,dd,ff,t,td,u,vv,ww,w1,w2,n,nbas,hbas,cl,cm,pres,tend24,tn12,tx12,tminsol,raf10,rafper,per,etat_sol,ht_neige,rr1,rr3,rr6,rr12,rr24,nnuage1,ctype1,hnuage1,nnuage2,hnuage2,nnuage3,hnuage3,coordonnees,nom,type_de_tendance_barometrique,temps_passe_1,temps_present,tc,tn12c,tx12c,tminsolc,latitude,longitude,altitude,libgeo,codegeo,nom_epci,code_epci,nom_dept,code_dep,nom_reg,code_reg,mois_de_l_annee
0,07020,2017-09-23 02:00:00+02:00,102290.0,0.0,4,160.0,4.9,287.25,283.45,78.0,18000.0,2,0,None,25.0,2,2500.0,30,23,102190.0,180.0,NaN,NaN,NaN,6.5,7.1,-10.0,None,NaN,0.0,0.0,0.0,NaN,NaN,2.0,3,2500.0,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00\x9f9\xebS\x8e\t\xff\xbf...,PTE DE LA HAGUE,"Stationnaire, la pression atmosphérique est la...",Nuages ne couvrant pas plus de la moitié du ci...,État du ciel inchangé dans l’ensemble,14.1,NaN,NaN,NaN,49.725167,-1.939833,6,La Hague,50041,CA du Cotentin,200067205,Manche,50,Normandie,28,9
1,07558,2017-09-23 02:00:00+02:00,102180.0,-40.0,8,30.0,2.4,285.75,282.95,83.0,20000.0,0,None,None,NaN,None,NaN,None,None,93940.0,160.0,NaN,NaN,283.75,3.5,3.5,-10.0,None,0.0,0.0,0.0,0.0,0.0,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,"b""\x01\x01\x00\x00\x00\x0e-\xb2\x9d\xef'\x08@\...",MILLAU,"Stationnaire ou en hausse, puis en baisse, ou ...",None,On n’a pas observé d’évolution des nuages ou o...,12.6,NaN,NaN,10.6,44.118500,3.019500,712,Millau,12145,CC de Millau Grands Causses,241200567,Aveyron,12,Occitanie,76,9
2,07661,2017-09-23 05:00:00+02:00,102090.0,-110.0,7,60.0,3.4,289.85,288.75,93.0,NaN,0,2,None,90.0,7,800.0,36,None,100500.0,150.0,NaN,NaN,NaN,4.5,4.8,-10.0,None,NaN,0.0,0.0,0.0,0.0,0.0,7.0,7,600.0,NaN,NaN,NaN,NaN,"b""\x01\x01\x00\x00\x00\x82\xfd\xd7\xb9i\xc3\x1...",CAP CEPET,En baisse,Nuages couvrant plus de la moitié du ciel pend...,On n’a pas observé d’évolution des nuages ou o...,16.7,NaN,NaN,NaN,43.079333,5.940833,115,Saint-Mandrier-sur-Mer,83153,Métropole Toulon-Provence-Méditerranée,248300543,Var,83,Provence-Alpes-Côte d'Azur,93,9
3,07117,2017-09-23 08:00:00+02:00,102070.0,-50.0,6,90.0,1.9,283.55,281.85,89.0,NaN,None,None,None,NaN,None,NaN,None,None,101360.0,-140.0,283.55,288.65,NaN,2.9,3.2,-10.0,None,NaN,0.0,0.0,0.0,0.0,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00\x18_\xb4\xc7\x0b\xc9\x0...,PLOUMANAC'H,"En baisse, puis stationnaire, ou en baisse, pu...",None,None,10.4,10.4,15.5,NaN,48.825833,-3.473167,55,Perros-Guirec,22168,CA Lannion-Trégor Communauté,200065928,Côtes-d'Armor,22,Bretagne,53,9
4,07621,2017-09-23 11:00:00+02:00,101950.0,-30.0,6,340.0,1.0,290.25,286.95,81.0,29000.0,0,None,None,NaN,None,NaN,None,None,97720.0,NaN,NaN,NaN,NaN,NaN,2.6,-10.0,None,0.0,0.0,0.0,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,b'\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00...,TARBES-OSSUN,"En baisse, puis stationnaire, ou en baisse, pu...",None,On n’a pas observé d’évolution des nuages ou o...,17.1,NaN,NaN,NaN,43.188000,0.000000,360,Louey,65284,CA Tarbes-Lourdes-Pyrénées,200069300,Hautes-Pyrénées,65,Occitanie,76,9

In [42]:
# Drop les colonnes géo redondantes; on garde le nom_dept, nom_region (redondant? mais utile pour le join?), longi/lati (utile pour les villes?)
# Pas mal de noms epci mais au final c'est juste des doublons formattés différemment
X_meteo.drop(
    columns=[
        "numer_sta",
        "coordonnees",
        "nom",
        "libgeo",
        "codegeo",
        "code_epci",
        "code_dep",
        "code_reg",
        "nom_epci",
    ],
    inplace=True,
)
# Drop var inutiles
X_meteo.drop(columns=["mois_de_l_annee", "t", "tminsol",
                      "tn12", "tx12"], inplace=True)

In [43]:
new_order = ['date', 'nom_dept', 'nom_reg', 'latitude', 'longitude',
        'altitude', 'pmer', 'tend', 'cod_tend',
        'dd', 'ff', 'td', 'u', 'vv',
       'n', 'nbas', 'hbas', 'cl', 'cm', 'pres', 'tend24',
       'raf10', 'rafper', 'per', 'etat_sol',
       'ht_neige', 'rr1', 'rr3', 'rr6', 'rr12', 'rr24', 'nnuage1', 'ctype1',
       'hnuage1', 'nnuage2', 'hnuage2', 'nnuage3', 'hnuage3',
       'type_de_tendance_barometrique', 'temps_present', 'ww', 'temps_passe_1',
       'w1', 'w2', 'tc',
       'tn12c', 'tx12c', 'tminsolc']
X_meteo = X_meteo[new_order]
X_meteo.head()

,date,nom_dept,nom_reg,latitude,longitude,altitude,pmer,tend,cod_tend,dd,ff,td,u,vv,n,nbas,hbas,cl,cm,pres,tend24,raf10,rafper,per,etat_sol,ht_neige,rr1,rr3,rr6,rr12,rr24,nnuage1,ctype1,hnuage1,nnuage2,hnuage2,nnuage3,hnuage3,type_de_tendance_barometrique,temps_present,ww,temps_passe_1,w1,w2,tc,tn12c,tx12c,tminsolc
0,2017-09-23 02:00:00+02:00,Manche,Normandie,49.725167,-1.939833,6,102290.0,0.0,4,160.0,4.9,283.45,78.0,18000.0,25.0,2,2500.0,30,23,102190.0,180.0,6.5,7.1,-10.0,None,NaN,0.0,0.0,0.0,NaN,NaN,2.0,3,2500.0,NaN,NaN,NaN,NaN,"Stationnaire, la pression atmosphérique est la...",État du ciel inchangé dans l’ensemble,2,Nuages ne couvrant pas plus de la moitié du ci...,0,None,14.1,NaN,NaN,NaN
1,2017-09-23 02:00:00+02:00,Aveyron,Occitanie,44.118500,3.019500,712,102180.0,-40.0,8,30.0,2.4,282.95,83.0,20000.0,NaN,None,NaN,None,None,93940.0,160.0,3.5,3.5,-10.0,None,0.0,0.0,0.0,0.0,0.0,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,"Stationnaire ou en hausse, puis en baisse, ou ...",On n’a pas observé d’évolution des nuages ou o...,0,None,None,None,12.6,NaN,NaN,10.6
2,2017-09-23 05:00:00+02:00,Var,Provence-Alpes-Côte d'Azur,43.079333,5.940833,115,102090.0,-110.0,7,60.0,3.4,288.75,93.0,NaN,90.0,7,800.0,36,None,100500.0,150.0,4.5,4.8,-10.0,None,NaN,0.0,0.0,0.0,0.0,0.0,7.0,7,600.0,NaN,NaN,NaN,NaN,En baisse,On n’a pas observé d’évolution des nuages ou o...,0,Nuages couvrant plus de la moitié du ciel pend...,2,None,16.7,NaN,NaN,NaN
3,2017-09-23 08:00:00+02:00,Côtes-d'Armor,Bretagne,48.825833,-3.473167,55,102070.0,-50.0,6,90.0,1.9,281.85,89.0,NaN,NaN,None,NaN,None,None,101360.0,-140.0,2.9,3.2,-10.0,None,NaN,0.0,0.0,0.0,0.0,0.0,NaN,None,NaN,NaN,NaN,NaN,NaN,"En baisse, puis stationnaire, ou en baisse, pu...",None,None,None,None,None,10.4,10.4,15.5,NaN
4,2017-09-23 11:00:00+02:00,Hautes-Pyrénées,Occitanie,43.188000,0.000000,360,101950.0,-30.0,6,340.0,1.0,286.95,81.0,29000.0,NaN,None,NaN,None,None,97720.0,NaN,NaN,2.6,-10.0,None,0.0,0.0,0.0,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,"En baisse, puis stationnaire, ou en baisse, pu...",On n’a pas observé d’évolution des nuages ou o...,0,None,None,None,17.1,NaN,NaN,NaN

In [44]:
# S'occuper de temps_present / passe et ww / w1 / w2